### ISSUE TITLE
Hola issues

### ISSUE THREAD

**Issue by Estebaniarosario** [maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-Estebaniarosario#1]
Pensé que lo hubiese creado pero por razones que desconozco cayo en la carpeta de uno de mi compañero

**Comment by geofis** [comment]
¡Perfecto! Ahora sí, correcto.

**Comment by Estebaniarosario** [comment]
Ok. Gracias





Enviado desde mi Samsung Mobile de Claro


-------- Mensaje original --------
De: José Ramón Martínez Batlle <notifications@github.com>
Fecha: 11/10/19 8:59 p. m. (GMT-04:00)
A: maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-Estebaniarosario <unidad-0-asignacion-1-asig-conrstudio-issues-Estebaniarosario@noreply.github.com>
CC: Estebaniarosario <agriestebania@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-Estebaniarosario] Hola issues (#1)


¡Perfecto! Ahora sí, correcto.
